import { getSupabase } from "./client";
import type { Quote, LineItem } from "@/types/quote";

interface SupabaseQuoteRow {
  id: string;
  slug: string;
  owner_token: string;
  customer_name: string;
  customer_phone: string | null;
  customer_email: string | null;
  customer_address: string | null;
  items: SupabaseQuoteItem[];
  notes: string | null;
  gst_inclusive: boolean;
  items_sum: number;  // Input: sum of line items
  subtotal: number;   // Generated by DB
  gst: number;        // Generated by DB
  total: number;      // Generated by DB
  status: string;
  created_at: string;
  updated_at: string;
}

interface SupabaseQuoteItem {
  id: string;
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
}

// Convert local Quote to Supabase format
// Note: subtotal, gst, total are GENERATED columns - don't send them
function toSupabaseFormat(quote: Quote, ownerToken: string): Record<string, unknown> {
  // Calculate items_sum from line items (frontend calculates the sum, DB calculates GST)
  const itemsSum = quote.items.reduce((sum, item) => sum + item.total, 0);

  return {
    id: quote.id,
    slug: quote.slug || quote.id.slice(0, 8),
    owner_token: ownerToken,
    customer_name: quote.customerName,
    customer_phone: quote.customerPhone || null,
    customer_email: quote.customerEmail || null,
    customer_address: quote.customerAddress || null,
    items: quote.items.map((item) => ({
      id: item.id,
      description: item.description,
      quantity: item.quantity,
      unit_price: item.unitPrice,
      total: item.total,
    })),
    notes: quote.notes || null,
    gst_inclusive: quote.gstInclusive,
    items_sum: itemsSum,  // Only send items_sum, DB calculates subtotal/gst/total
    status: quote.status,
    created_at: quote.createdAt,
    updated_at: quote.updatedAt,
  };
}

// Convert Supabase format to local Quote (excludes owner_token for security)
function fromSupabaseFormat(row: SupabaseQuoteRow): Quote {
  return {
    id: row.id,
    slug: row.slug,
    // Note: owner_token is NOT included here - it stays in localStorage only
    customerName: row.customer_name,
    customerPhone: row.customer_phone ?? undefined,
    customerEmail: row.customer_email ?? undefined,
    customerAddress: row.customer_address ?? undefined,
    items: (row.items || []).map((item): LineItem => ({
      id: item.id,
      description: item.description,
      quantity: item.quantity,
      unitPrice: item.unit_price,
      total: item.total,
    })),
    notes: row.notes ?? undefined,
    gstInclusive: row.gst_inclusive,
    subtotal: Number(row.subtotal),
    gst: Number(row.gst),
    total: Number(row.total),
    status: row.status as "draft" | "sent" | "accepted",
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

// Save quote to Supabase (INSERT or UPDATE)
export async function saveQuoteToSupabase(
  quote: Quote,
  ownerToken: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = getSupabase();
  if (!supabase) {
    return { success: false, error: "Supabase not configured" };
  }

  try {
    const data = toSupabaseFormat(quote, ownerToken);

    const { error } = await supabase
      .from("quotes")
      .upsert(data, { onConflict: "id" });

    if (error) {
      console.error("Supabase save error:", error);
      return { success: false, error: error.message };
    }

    return { success: true };
  } catch (err) {
    console.error("Supabase save exception:", err);
    return { success: false, error: "Failed to save to cloud" };
  }
}

// Update quote in Supabase (requires owner_token or authenticated user)
// Note: subtotal, gst, total are GENERATED columns - don't send them
export async function updateQuoteInSupabase(
  quote: Quote,
  ownerToken: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = getSupabase();
  if (!supabase) {
    return { success: false, error: "Supabase not configured" };
  }

  // Calculate items_sum from line items
  const itemsSum = quote.items.reduce((sum, item) => sum + item.total, 0);

  try {
    const { data: { user } } = await supabase.auth.getUser();

    // Prepare data
    const updateData = {
      customer_name: quote.customerName,
      customer_phone: quote.customerPhone || null,
      customer_email: quote.customerEmail || null,
      customer_address: quote.customerAddress || null,
      items: quote.items.map((item) => ({
        id: item.id,
        description: item.description,
        quantity: item.quantity,
        unit_price: item.unitPrice,
        total: item.total,
      })),
      notes: quote.notes || null,
      gst_inclusive: quote.gstInclusive,
      items_sum: itemsSum,
      status: quote.status,
    };

    if (user) {
      // Authenticated: Use standard RLS update
      const { error } = await supabase
        .from("quotes")
        .update(updateData)
        .eq("id", quote.id); // RLS checks user_id

      if (error) throw error;
    } else {
      // Anonymous: Use secure RPC
      const { data: success, error } = await supabase.rpc("update_quote_anon", {
        p_id: quote.id,
        p_token: ownerToken,
        p_payload: updateData,
      });

      if (error) throw error;
      if (!success) return { success: false, error: "Quote not found or access denied" };
    }

    return { success: true };
  } catch (err) {
    console.error("Supabase update exception:", err);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return { success: false, error: (err as any).message || "Failed to update in cloud" };
  }
}

// ...

// Delete quote from Supabase (requires owner_token or authenticated user)
export async function deleteQuoteFromSupabase(
  id: string,
  ownerToken: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = getSupabase();
  if (!supabase) {
    return { success: false, error: "Supabase not configured" };
  }

  try {
    const { data: { user } } = await supabase.auth.getUser();

    if (user) {
      // Authenticated: Use standard RLS delete
      const { error } = await supabase
        .from("quotes")
        .delete()
        .eq("id", id); // RLS checks user_id

      if (error) throw error;
    } else {
      // Anonymous: Use secure RPC
      const { data: success, error } = await supabase.rpc("delete_quote_anon", {
        p_id: id,
        p_token: ownerToken,
      });

      if (error) throw error;
      if (!success) return { success: false, error: "Quote not found or access denied" };
    }

    return { success: true };
  } catch (err) {
    return { success: false, error: "Failed to delete from cloud" };
  }
}

// Get all quotes from Supabase (for a list of owner tokens)
export async function getQuotesByOwnerTokens(ownerTokens: string[]): Promise<Quote[]> {
  const supabase = getSupabase();
  if (!supabase || ownerTokens.length === 0) {
    return [];
  }

  try {
    const { data, error } = await supabase
      .from("quotes")
      .select("*")
      .in("owner_token", ownerTokens)
      .order("created_at", { ascending: false });

    if (error || !data) {
      return [];
    }

    return (data as SupabaseQuoteRow[]).map(fromSupabaseFormat);
  } catch {
    return [];
  }
}
